export const pickUpSpot = [
  {
    title: "광안리 해수욕장 입구",
    address: "부산광역시 수영구 광안해변로 219",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "200L",
    latitude: 35.1532,
    longitude: 129.1186,
  },
  {
    title: "해운대 해수욕장 중앙",
    address: "부산광역시 해운대구 우동 1408-5",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "150L",
    latitude: 35.1587,
    longitude: 129.1604,
  },
  {
    title: "송정 해수욕장 앞",
    address: "부산광역시 해운대구 송정동 712-2",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "120L",
    latitude: 35.1834,
    longitude: 129.1991,
  },
  {
    title: "오륙도 선착장",
    address: "부산광역시 남구 용호동 936-1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "180L",
    latitude: 35.1075,
    longitude: 129.1244,
  },
  {
    title: "다대포 해수욕장 입구",
    address: "부산광역시 사하구 다대동 682-3",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "210L",
    latitude: 35.0473,
    longitude: 128.9676,
  },
  {
    title: "송도 해수욕장 중앙",
    address: "부산광역시 서구 암남동 129-4",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "170L",
    latitude: 35.0771,
    longitude: 129.0202,
  },
  {
    title: "남포동 자갈치 시장 앞",
    address: "부산광역시 중구 남포동4가 37-1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "190L",
    latitude: 35.0975,
    longitude: 129.0329,
  },
  {
    title: "부산항 국제여객터미널",
    address: "부산광역시 동구 초량동 1190",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "220L",
    latitude: 35.1066,
    longitude: 129.0377,
  },
  {
    title: "태종대 전망대",
    address: "부산광역시 영도구 동삼동 1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "250L",
    latitude: 35.0511,
    longitude: 129.0861,
  },
  {
    title: "영도 해양공원",
    address: "부산광역시 영도구 동삼동 27",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "140L",
    latitude: 35.0481,
    longitude: 129.0815,
  },
  {
    title: "다대포 꿈의 낙조 분수",
    address: "부산광역시 사하구 다대동 19",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "180L",
    latitude: 35.0496,
    longitude: 128.9669,
  },
  {
    title: "부산 북항 재개발 구역",
    address: "부산광역시 동구 초량동 1112",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "230L",
    latitude: 35.1025,
    longitude: 129.0405,
  },
  {
    title: "송도 해상케이블카 탑승장",
    address: "부산광역시 서구 암남동 105-6",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "160L",
    latitude: 35.0796,
    longitude: 129.0161,
  },
  {
    title: "부산국제영화제 광장",
    address: "부산광역시 중구 남포동5가 35-1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "200L",
    latitude: 35.0972,
    longitude: 129.0331,
  },
  {
    title: "감천문화마을 입구",
    address: "부산광역시 사하구 감천동 10-14",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "210L",
    latitude: 35.0974,
    longitude: 128.9834,
  },
  {
    title: "해운대 달맞이길 입구",
    address: "부산광역시 해운대구 중동 1013-2",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "140L",
    latitude: 35.1611,
    longitude: 129.1757,
  },
  {
    title: "광안대교 하부",
    address: "부산광역시 수영구 민락동 193-10",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "250L",
    latitude: 35.1554,
    longitude: 129.1204,
  },
  {
    title: "동백섬 입구",
    address: "부산광역시 해운대구 우동 710-1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "160L",
    latitude: 35.1575,
    longitude: 129.1558,
  },
  {
    title: "수영강 하구",
    address: "부산광역시 수영구 망미동 100",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "230L",
    latitude: 35.1678,
    longitude: 129.1274,
  },
  {
    title: "부산 영도 흰여울문화마을",
    address: "부산광역시 영도구 영선동4가 135",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "190L",
    latitude: 35.0763,
    longitude: 129.0669,
  },
  {
    title: "부산역 광장",
    address: "부산광역시 동구 초량동 1211-1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "220L",
    latitude: 35.1157,
    longitude: 129.0413,
  },
  {
    title: "마린시티 해안로",
    address: "부산광역시 해운대구 우동 1408-4",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "210L",
    latitude: 35.1563,
    longitude: 129.1504,
  },
  {
    title: "남천동 해수변 공원",
    address: "부산광역시 수영구 남천동 11-1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "160L",
    latitude: 35.1468,
    longitude: 129.1073,
  },
  {
    title: "센텀시티 백스코 앞",
    address: "부산광역시 해운대구 우동 1500",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "180L",
    latitude: 35.1708,
    longitude: 129.1282,
  },
  {
    title: "송정해수욕장 서쪽",
    address: "부산광역시 해운대구 송정동 708",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "150L",
    latitude: 35.1875,
    longitude: 129.1993,
  },
  {
    title: "온천천 수변공원",
    address: "부산광역시 동래구 사직동 14-7",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "190L",
    latitude: 35.2033,
    longitude: 129.0778,
  },
  {
    title: "부산 요트경기장",
    address: "부산광역시 해운대구 우동 1411-1",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "160L",
    latitude: 35.1539,
    longitude: 129.1449,
  },
  {
    title: "부산 해양박물관 앞",
    address: "부산광역시 영도구 동삼동 1-4",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "대형 투기쓰레기류",
    realTrashAmount: "170L",
    latitude: 35.0739,
    longitude: 129.0855,
  },
  {
    title: "해운대 해수욕장 동쪽 끝",
    address: "부산광역시 해운대구 중동 1015-3",
    imgs: "../../assets/images/CardImages.jpg",
    mainTrashType: "일반 쓰레기",
    realTrashAmount: "120L",
    latitude: 35.1611,
    longitude: 129.1773,
  },
];
